<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.4 on linux)" generated="20220909 18:11:26.989" rpa="false" schemaversion="3">
<suite id="s1" name="Tests" source="/home/dmd-pc-testeur/VSCode Projects/mon_API/Tests">
<suite id="s1-s1" name="Api" source="/home/dmd-pc-testeur/VSCode Projects/mon_API/Tests/api.robot">
<test id="s1-s1-t1" name="Inscrire un utilisateur dans la BD" line="6">
<kw name="Vérifier l'existance de l'utilisateur dans la base de données" library="singupBack">
<kw name="Connect To Database Using Custom Params">
<arg>pymysql</arg>
<arg>database='demo', user='root', password='', host='localhost'</arg>
<msg timestamp="20220909 18:11:27.004" level="FAIL">No keyword with name 'Connect To Database Using Custom Params' found.</msg>
<status status="FAIL" starttime="20220909 18:11:27.004" endtime="20220909 18:11:27.004"/>
</kw>
<kw name="Row Count Is 0">
<arg>SELECT `id` FROM `users` WHERE `username` = ${USERNAME} AND `password` = md5(${PASSWORD})</arg>
<status status="NOT RUN" starttime="20220909 18:11:27.004" endtime="20220909 18:11:27.004"/>
</kw>
<status status="FAIL" starttime="20220909 18:11:27.003" endtime="20220909 18:11:27.005"/>
</kw>
<kw name="Inscription utilisateur par une requête Http POST" library="singupBack">
<status status="NOT RUN" starttime="20220909 18:11:27.005" endtime="20220909 18:11:27.005"/>
</kw>
<kw name="Vérifier que l'utilisateur est ajoute dans la BD" library="singupBack">
<status status="NOT RUN" starttime="20220909 18:11:27.005" endtime="20220909 18:11:27.005"/>
</kw>
<tag>First</tag>
<status status="FAIL" starttime="20220909 18:11:27.002" endtime="20220909 18:11:27.005">No keyword with name 'Connect To Database Using Custom Params' found.</status>
</test>
<status status="FAIL" starttime="20220909 18:11:26.999" endtime="20220909 18:11:27.005"/>
</suite>
<status status="FAIL" starttime="20220909 18:11:26.990" endtime="20220909 18:11:27.006"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">First</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Tests">Tests</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Api">Tests.Api</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220909 18:11:27.001" level="ERROR">Error in file '/home/dmd-pc-testeur/VSCode Projects/mon_API/Ressources/singupBack.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python310.zip
  /usr/lib/python3.10
  /usr/lib/python3.10/lib-dynload
  /usr/local/lib/python3.10/dist-packages
  /usr/lib/python3/dist-packages</msg>
<msg timestamp="20220909 18:11:27.001" level="ERROR">Error in file '/home/dmd-pc-testeur/VSCode Projects/mon_API/Ressources/singupBack.robot' on line 3: Importing library 'RequestsLibrary' failed: ModuleNotFoundError: No module named 'RequestsLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python310.zip
  /usr/lib/python3.10
  /usr/lib/python3.10/lib-dynload
  /usr/local/lib/python3.10/dist-packages
  /usr/lib/python3/dist-packages</msg>
<msg timestamp="20220909 18:11:27.001" level="ERROR">Error in file '/home/dmd-pc-testeur/VSCode Projects/mon_API/Ressources/singupBack.robot' on line 4: Importing library 'DatabaseLibrary' failed: ModuleNotFoundError: No module named 'DatabaseLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python310.zip
  /usr/lib/python3.10
  /usr/lib/python3.10/lib-dynload
  /usr/local/lib/python3.10/dist-packages
  /usr/lib/python3/dist-packages</msg>
<msg timestamp="20220909 18:11:27.002" level="ERROR">Error in file '/home/dmd-pc-testeur/VSCode Projects/mon_API/Ressources/singupBack.robot' on line 6: Importing library 'pymysql' failed: ModuleNotFoundError: No module named 'pymysql'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python310.zip
  /usr/lib/python3.10
  /usr/lib/python3.10/lib-dynload
  /usr/local/lib/python3.10/dist-packages
  /usr/lib/python3/dist-packages</msg>
</errors>
</robot>
